services:
  frontend:
    build: ./containers/frontend
    expose:
      - "80"
    networks:
      - transcendence

  nginx:
    build: ./containers/nginx
    expose:
      - "80"
    ports:
      - "8443:443"
    networks:
      - transcendence

  database:
    build: ./containers/database
    expose:
    - "5432"
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge

